export const FETCH_PRODUCTS = 'PRODUCT/FETCH_PRODUCTS'
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const FETCH_SINGLE_PRODUCT = 'PRODUCT/FETCH_SINGLE_PRODUCT'